import { Link } from 'react-router-dom'
import './App.css'

function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-50 shadow-sm">
        <div className="max-w-4xl mx-auto px-6">
          <div className="flex items-center justify-between py-4">
            <Link to="/" className="flex items-center gap-2 text-2xl font-bold text-gray-900">
              <span className="text-3xl">💊</span>
              <span className="bg-gradient-to-r from-blue-600 to-green-500 bg-clip-text text-transparent">
                MediPing
              </span>
            </Link>
            <Link to="/" className="text-gray-600 hover:text-blue-600 text-sm font-medium">
              ← Back to Home
            </Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
          <p className="text-gray-600 mb-8">Updated at {new Date().toLocaleDateString()}</p>

          <div className="space-y-8">
            {/* Introduction */}
            <section>
              <p className="text-gray-700 leading-relaxed">
                MediPing ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by MediPing. This Privacy Policy applies to our website, mediping.online, and its associated subdomains (collectively, our "Service") alongside our application, MediPing. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
              </p>
            </section>

            {/* Definitions */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Definitions and Key Terms</h2>
              <p className="text-gray-700 mb-4">To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
              
              <ul className="space-y-3 text-gray-700">
                <li>
                  <strong>Cookie:</strong> A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                </li>
                <li>
                  <strong>Company:</strong> When this policy mentions "Company," "we," "us," or "our," it refers to MediPing that is responsible for your information under this Privacy Policy.
                </li>
                <li>
                  <strong>Country:</strong> Where MediPing or the owners/founders of MediPing are based, in this case is United States.
                </li>
                <li>
                  <strong>Customer:</strong> Refers to the company, organization or person that signs up to use the MediPing Service to manage the relationships with your consumers or service users.
                </li>
                <li>
                  <strong>Device:</strong> Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit mediping.online and use the services.
                </li>
                <li>
                  <strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                </li>
                <li>
                  <strong>Personnel:</strong> Refers to those individuals who are employed by MediPing or are under contract to perform a service on behalf of one of the parties.
                </li>
                <li>
                  <strong>Personal Data:</strong> Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                </li>
                <li>
                  <strong>Service:</strong> Refers to the service provided by MediPing as described in the relative terms (if available) and on this platform.
                </li>
                <li>
                  <strong>Third-party service:</strong> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                </li>
              </ul>
            </section>

            {/* What Information We Collect */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">What Information Do We Collect?</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Information You Provide to Us</h3>
              <p className="text-gray-700 mb-4">
                We collect information that you provide directly to us, including:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
                <li>Account information (name, email address, phone number)</li>
                <li>Profile information (age, gender, timezone)</li>
                <li>Medication information (medication names, dosages, schedules)</li>
                <li>Health information you choose to share</li>
                <li>Payment information (processed securely through third-party payment processors)</li>
                <li>Communications with us (support requests, feedback)</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Information Automatically Collected</h3>
              <p className="text-gray-700 mb-4">
                There is some information like your Internet Protocol (IP) address and/or browser and device characteristics that is collected automatically when you visit our platform. This information may be used to connect your computer to the Internet. Other information collected automatically could be a login, e-mail address, password, computer and connection information such as browser plug-in types and versions and time zone setting, operating systems and platforms, purchase history, (we sometimes aggregate with similar information from other Users), the full Uniform Resource Locator (URL) clickstream to, through and from our Website that may include date and time; Cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Services.
              </p>
              <p className="text-gray-700 mb-4">
                We may also use browser data such as cookies, Flash cookies (also known as Flash Local Shared Objects) or similar data on certain parts of our Website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page. We may also collect technical information to help us identify your device for fraud prevention and diagnostic purposes.
              </p>
              <p className="text-gray-700 mb-4">
                We automatically collect certain information when you visit, use or navigate the platform. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about who and when you use our and other technical information. This information is primarily needed to maintain the security and operation of our platform, and for our internal analytics and reporting purposes.
              </p>
            </section>

            {/* How We Use Information */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">How Do We Use Your Information?</h2>
              <p className="text-gray-700 mb-4">We use the information we collect to:</p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li>Provide, maintain, and improve our services</li>
                <li>Process transactions and send related information</li>
                <li>Send you technical notices, updates, and support messages</li>
                <li>Respond to your comments, questions, and requests</li>
                <li>Monitor and analyze trends, usage, and activities</li>
                <li>Detect, prevent, and address technical issues and fraudulent activity</li>
                <li>Personalize and improve your experience</li>
                <li>Send you promotional communications (with your consent)</li>
                <li>Comply with legal obligations</li>
              </ul>
            </section>

            {/* Information Sharing */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Will Your Information Be Shared With Anyone?</h2>
              <p className="text-gray-700 mb-4">
                We do not sell, trade, or rent your personal information to third parties. We may share your information in the following circumstances:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li><strong>Service Providers:</strong> We may share information with third-party service providers who perform services on our behalf, such as payment processing, data analysis, email delivery, and hosting services.</li>
                <li><strong>Caregivers:</strong> If you choose to share your medication schedule with caregivers, they will have access to the information you explicitly share with them.</li>
                <li><strong>Legal Requirements:</strong> We may disclose information if required by law or in response to valid requests by public authorities.</li>
                <li><strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction.</li>
                <li><strong>With Your Consent:</strong> We may share information with your explicit consent.</li>
              </ul>
            </section>

            {/* Cookies */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Cookies and Tracking Technologies</h2>
              <p className="text-gray-700 mb-4">
                We use cookies and similar tracking technologies to track activity on our Service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
              </p>
              <p className="text-gray-700 mb-4">
                We use Sessions to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.
              </p>
            </section>

            {/* Data Security */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">How Do We Keep Your Information Safe?</h2>
              <p className="text-gray-700 mb-4">
                We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.
              </p>
            </section>

            {/* GDPR */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Information about General Data Protection Regulation (GDPR)</h2>
              <p className="text-gray-700 mb-4">
                We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">What is GDPR?</h3>
              <p className="text-gray-700 mb-4">
                GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have, over their personal data. The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers' data is important irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">What is personal data?</h3>
              <p className="text-gray-700 mb-4">
                Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person's name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">The Data Protection Principles include requirements such as:</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-4">
                <li>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</li>
                <li>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</li>
                <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
                <li>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Why is GDPR important?</h3>
              <p className="text-gray-700 mb-4">
                GDPR introduces new requirements for companies to protect personal data, increases enforcement, and imposes greater fines for breaches. We believe data privacy is important and already have strong security and privacy practices in place.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Individual Data Subject's Rights - Data Access, Portability and Deletion</h3>
              <p className="text-gray-700 mb-4">
                We are committed to meeting GDPR data subject rights. We store conversation and personal data for up to 6 years unless an account is deleted, in which case data is disposed of within 60 days according to our Terms of Service and Privacy Policy. For EU customers, we provide self-service access to data and customer data, and our support team is available for API-related questions.
              </p>
            </section>

            {/* CCPA */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">California Residents</h2>
              <p className="text-gray-700 mb-4">
                The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect, how it's used, categories of sources, and third parties with whom it's shared.
              </p>
              <p className="text-gray-700 mb-4">
                <strong>We do not sell the Personal Information of our users.</strong>
              </p>
              <p className="text-gray-700 mb-4">If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">California Online Privacy Protection Act (CalOPPA)</h3>
              <p className="text-gray-700 mb-4">
                CalOPPA requires disclosure of categories of Personal Information collected, how it's used, categories of sources, and third parties with whom it's shared.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Your Rights Under California Law:</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-700">
                <li><strong>Right to Know and Access:</strong> You can submit a verifiable request for information regarding (1) categories of Personal Information collected, used, or shared; (2) purposes for which categories of Personal Information are collected or used; (3) categories of sources from which Personal Information is collected; and (4) specific pieces of Personal Information collected about you.</li>
                <li><strong>Right to Equal Service:</strong> We will not discriminate against you for exercising your privacy rights.</li>
                <li><strong>Right to Delete:</strong> You can submit a verifiable request to close your account, and we will delete collected Personal Information.</li>
                <li><strong>Right to Opt-Out:</strong> You have the right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
              </ul>
            </section>

            {/* Children's Privacy */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Children's Privacy</h2>
              <p className="text-gray-700 mb-4">
                Our Service is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us so we can delete such information.
              </p>
            </section>

            {/* Changes to Privacy Policy */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Changes to This Privacy Policy</h2>
              <p className="text-gray-700 mb-4">
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Updated at" date. You are advised to review this Privacy Policy periodically for any changes.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
              <p className="text-gray-700 mb-4">
                If you have any questions about this Privacy Policy, please contact us:
              </p>
              <ul className="list-none space-y-2 text-gray-700">
                <li><strong>Email:</strong> privacy@mediping.online</li>
                <li><strong>Website:</strong> mediping.online</li>
              </ul>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-50 border-t border-gray-200 py-8 mt-16">
        <div className="max-w-4xl mx-auto px-6">
          <p className="text-center text-gray-600 text-sm">
            © 2025 MediPing. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}

export default PrivacyPolicy

